# Generated by Django 3.2.15 on 2023-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='سبد خرید', max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='')),
                ('update date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('content_text', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='count',
        ),
    ]
